apiVersion: v1
kind: ConfigMap
metadata:
  name: v2ray-config
  labels:
    {{- include "v2ray.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "dns": {
        "servers": [
          {{- range $i, $s := .Values.server.dnsServers }}
          {{- if $i }},{{ end }}
          "{{ $s }}"
          {{- end }}
        ]
      },
      "inbounds": [
        {
          "port": {{ .Values.server.port }},
          "protocol": "vmess",
          "settings": {
            "clients": [
              {
                "alterId": {{ .Values.server.alterId }},
                "id": "__V2RAY_ID__"
              }
            ]
          },
          "streamSettings": {
            "network": "ws",
            "security": "none",
            "wsSettings": {
              "path": "{{ .Values.server.websocketPath }}"
            }
          }
        }
      ],
      "outbounds": [
        {
          "protocol": "freedom",
          "settings": {}
        }
      ]
    }
