apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: homelab
spec:
  serviceSelector:
    matchLabels:
      homelab.dsns.dev/load-balancer: cilium
  nodeSelector:
    matchExpressions:
      - key: node.kubernetes.io/exclude-from-external-load-balancers
        operator: DoesNotExist
  # Use Cilium's detected devices on the shared LAN.
  loadBalancerIPs: true
  externalIPs: false
