---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBrDv4CUt/UozmG23EdAImyxbvc+QFDixPjYoxtn1x5yX8FtFCd+yusCyMAraXi53Wg7Xt2d0hgy/4xIa+KPg/qFhviMYPtBvIx3p09xzAKIq/w4JcEigAf+kAS6XRnQYrFTie/PSBwFxfTo25PEJi9svD0iOui7Ng1MeKwJvXBoWFNJNJVr9fh1QNfwS/PHa7bM7IYzhF6BbVJFFXs3Dxdhip6EISWZUKgJi4pagrB3Mg95ezfXgLtOGd/7MrqqrPIaXlcLKk6Y9VfeEoSRD1Rnt04rndhczR8Rf4KuKr2Qc3dOBUHiTKMDg4CoxNs/X3Ir7BbfH7nDkp1lDPz07GOBxzOOR6zmCdz616zXHq2sZtowUsT5oRt8PJQg6VHkrAzUAQKF1j3VxOYqctZ6UORdBhL5uTRWa4+B2oun7Pn0NNs5K64ma3Xst/hwnKbp+qLEz93qBbeqwTFd8F1HuZ9XqG9YgLpOhwtlPc42PhtROs678qpETXXjp2vE3J5MuD2cax9R3pv1dctzJoz/W17H/JQ0TcEMWQqNW3ClbWmUZMRihIHoox8DevgutrtFStoyt67CP91Z+halsnX+M7PShNpPFNc9O2lcFPSxkJMMj1bI8bS4ZBSXxdZUs+ydYs2BvGNU/FBjUBhShgf27gZOR75zHNXFrWG9eMmCH0WoZ8afvzZ5oq8JgNGvDBapRV4CmLHopvWRv0UPNEEe1fSaNfzAjik6CQ2d/nAZpZSY+xD/7xlCVLg
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
