clusterIssuer:
  name: letsencrypt-prod
  email: dominic@seung.dev
  server: https://acme-v02.api.letsencrypt.org/directory
  privateKeySecretRef: letsencrypt-prod-key
  cloudflareSecret:
    name: cloudflare-api-token
    key: api-token
