---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: v2ray-config
  namespace: v2ray-vpn
spec:
  encryptedData:
    config.json: AgApayOIhnMMr42ZMO4D53ORudKiYMvL3arJbr5CRtCB1LByHfdnC4I+Dxlo2epvXx2TAGGhL7ebWcTUoW3KoJUjQs+tnzibyAXVnCS9WEFJOWBCNTc6FxxTEtksjpi2KyJtDLrkh55ywvdP5UBjFsk78c5ljm9hV69ipqbRlwRWbALtjYz6sYuaJI8cpC9ECGTLAAjhALQy57BnBNuLeZ8/mJNf6TGJJCQQKAeMI7Jk+SjTAIo7Ik+FNqNyCHKvcT0MN1Gq560VBZodVR1gtqpWxGV2q9IlEHxEVwXlK4rBXAYnvfcpHIIUFx3mo2F78r5cCnLvjeUvzw7weWYMXHLm+Fhdrw8nw5l5nDiheDYa7ZfInYe2g98QQ3YRMKFRzEo1OK4k37t4SExTB9BROrO3EWLNMCUUoZnCgS4zTKvmRURINSvCjqHpt8Ck4KmyKAF1HnTxC1x5mCNgDvQMPtsuUSFkmNE2EStuOSDusJHj4q8g8PV2y5ESjsdYr5DR88nXycvGOj6TB9bvhkj/QDj3QAqn9q/+b6KO6RGuIz1cPFEEm49FRHQ7zDY5+D832/Slv5GxzfQVPevGyobmVKpXqL4D3r5P5yshXoo+qvHkVHjqgVYF7gymj6qqx5j0CCr9wu3IRM++OHsxACHx/mOKGgontWuByoQmNfC0dVIeynkqVlwdDmLv8xsXtnMHC1pTOSGBBpuJsK4b5FHqh2gUlLDiKhzsvM89bUgbq1jUbdn68++q04ZAEjpHTMU/kNXqnGzRP7RpogFM4e5rITDjhwZEy87Cbo30M5AGsSAp8BZlI0rPY6WJzvWtjXPmku3gGufmnm44OM/Qf0kw01eu3MjpfWvVmowXf/mybiH21cncazvFr3VGgDQSkUP9rg6mNnanQ6yZ8Azq/K2SqXWjyaetwBbV8r6Yq02qubFLvtq+KuiB3jfcEeK8gWK5XRixd9dXvL/cilB5A5KHFOlfYsknM5b5LPWTlU8ZLf507BAmPE3zp2zQFkmq/VEytXaubrrsdXaH1FRlcfTOeaXDGNv7KE3dvSB2Rgbo1drK3SsgRyo+qgOIGxjb7jGSRoCaTD94Cp3jvDPHyIfC8Z7t12zRGEDCC1U3iUi/j1jdc7+jetbp8jIS2ELH+DJmpzvRZUvEPQrPRqDBsUYGPfvixSnta1a3dNFPqHl7Ya4kM+961fFW9gdSvSUnQa57I4nqMkAXTJFklUXg2cyxZXDNqIeHVVR5Yt7p3CHb6Me9w4Sl9H8p8EeWOzLsgUTAOFDi16VGoq4nZzt++OedvCYiYE8DtBmXQrQRJddB5hhQQETS0W1K0dzmxa5XSV40BWVDnkmAfLJ2v7jtxwf68SwZomRh6m9NVxnADxzSsAJg3nxCAUYhKWWmjYwhjnU6O2k84/ew3Q8ItWi7413YxMLLj1CVbVQrCz+8pw==
  template:
    metadata:
      name: v2ray-config
      namespace: v2ray-vpn
    type: Opaque
