---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: v2ray-config
  namespace: v2ray-vpn
spec:
  encryptedData:
    config.json: AgCoX+uhqKGI4whoiyisRoLJqEbiwf6I8xH4lRne4sI9sjsH6NOe8n2ODws0uSAdQKOXv7aaycDCadapdk7giyrpzX2yclT/51tTsDWCyUztzu+s3RIUt+wkk96h/smQoqA9Uuz0cUmTUr3eNvhO8xDnj/dzeJO5erdSSa0WAgrYDHAHt8MOtERHcu2TkPr2phSmlLz56+lVikpTMCJmT7Z1c2nGnDyi1B3a1w+1CkLUVuvdZQ8cnoKot7FsIeNfY0WbRSp8i5YBUMPp2Mllnxv0DAfJ9IEDl3ol9FgZbEgUh8qV+pIBOfQOKXbC+MJMJCG2v+Q6trxUz2gECgvTBXVXVaQ+yTJGYN/SQG+XkpmH7p6c4PvV/2SNH+A56Fph6JptJV69d7Msjkc9VbJJ36JJ4r0CTiY7NwSM1gJ5iUC48iB4nqSfXeTfVFH7B5ZiRbMvviDo8zykh29OAL6JdCAGWrsjW0KZFe1bYFNQFiQklFFn8pxUXZAkI2uavgja+HF1xFt4nqU697JLJAA4lXYpq80eYoUD18p1/AS/cmHShqf03ynyeJoRyloVU6kcotUmyG7cCmCvMXCQ4b1UyLzo0FNHDVpLWjMadJKmtnd1Q+obPQcAeQMhunYtK3wntYNVXpvlgCWhFS+EOwa+Kx8Y3jw3Qn5r/fDZPguFTeeYiQlLW/+LZNtRxlI66GM3ZhIBpb/uI66wm4Gr3i7vQ1NN1rpXAXJU2cLuuwofn2jgeDbWXRzJCgbLoHS72CY7ZKUiwDnSlwNsgOr6g4LMDOwUeHkxo58GocmXXumb/b1x0n/P1nFM6ix8ssyq+fUGP8p+qcvAobGkyN9ru7iSCzG3lO2w0Puqnth5EwRuXPu+A4Nj2ksvY7KpYslkyxnKU8oTugl+CeJnK6s5zEUKUdXg0E9/blV9Yb8eTLUk0G3GvyOEAP4NG8h2Ts7ezaJntsD/8gVgdbBoS1DrRAgzDlobD1gGzKuor1xtU4lOou/hZzVTHTmTHwFo/Ym8mG2ZPSD5Yhq/3ziCal9KR59QkI7SOiYhYzZx3EPl/AW8kCtRf0Zj597eBmnosGFemZcn7XnzUE3kSlLk1+30tXZ/8lCe/FfknzZ/hmSaD9CBY2L3bR/lYPfjiSO+nRF8FZk43WGgLHDgNpCMMey1qHOIiXBi6HLincx4Ctsk6wEVcJ1vUfDCA+mPgFUKwW9eicNvIDAPghbXZ0remguvfJxEu+4JwqDd/p4dmO/wQfyYNzIRVzh3KqctbRW9tBWMbkFUQTN2/IA7cyl+4Hyo0anZV39Y3P+Fk60rAEq41zIkVQ41rjXRy8u4Xybk8plO/jie7q7CaY77DxJLLTkCQabScSr9zXotf+rka9lWcslK40ZQCl+AzkCcRX8+XafJjMh064QJOlv3xwN0bGghmr5HE81fdQISamdw7tCN3w==
  template:
    metadata:
      name: v2ray-config
      namespace: v2ray-vpn
    type: Opaque
