apiVersion: v1
kind: Service
metadata:
  name: v2ray-service
  namespace: v2ray-vpn
spec:
  type: LoadBalancer
  loadBalancerIP: 10.3.3.10
  selector:
    app: v2ray
  ports:
  - name: v2ray
    port: 10086
    targetPort: 10086
