apiVersion: v1
kind: ConfigMap
metadata:
  name: v2ray-config
  namespace: v2ray-vpn
data:
  # The v2ray initContainer replaces __V2RAY_ID__ with the content of the
  # v2ray-id Secret before starting.
  config.json: |
    {
      "dns": {
        "servers": [
          "https://dns.adguard.com"
        ]
      },
      "inbounds": [
        {
          "port": 10086,
          "protocol": "vmess",
          "settings": {
            "clients": [
              {
                "alterId": 64,
                "id": "__V2RAY_ID__"
              }
            ]
          },
          "streamSettings": {
            "network": "ws",
            "security": "none",
            "wsSettings": {
              "path": "/dsns"
            }
          }
        }
      ],
      "outbounds": [
        {
          "protocol": "freedom",
          "settings": {}
        }
      ]
    }
