---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: v2ray-config
  namespace: v2ray-vpn
spec:
  encryptedData:
    config.json: AgAp4J5qYS1XtS5kThZltM4Wwjn6USVNQXBGnqrFbc5YyHX/W40f/Ub0ucISuimU6KYd966mjzId8ETAbBuDsJqlPFR+damdW+aPiNVzTpi+67/U1htMm9UQGeEdB9ewSlBZ4DHR8s/t5PXROSTAbiaIW7vEAXECJDrXW2DBEpJOzGEY+fxM5Grr1yXt/MpiDhBE5qM78B7VqPEpVGpZ4dsyXVl9vZ4aHJ1XPP0u3kVA7qlTP7kxsE/nWmxKHFN59/t3xs3MKZS0EN/yRSiwixZTbwHn8Vv9uBI1AcIfGBmimP+mfL6uaY9JvUkNVm47KIGeUV7SYkH7MolHVY6FF6YsA+Wn0AWr2nQNawttzYxQkTQMgvQo0ns/xR6j9Q46h8mcQGahLbb//QdfdjtVoA2pxlQgIlDgHpM0Luk+lazCT8oAwwsCzJVY8iWEV1q2pmnmztU9FNyK5NyXEKTiE4PO3KY0n4E7lC7osXpa2ARK2htJH33u9IAyGa5OVLEI3zK8G5rNN+HF8Mf4FTrZoOwpNTSe4M02oBKHiZS1jMH6xchUyB9D4+C040sPX/K7xxM7q5BRHQHsmk+6b7KDGvN6+/uSwolNlk+NZD7STbqjhs6+YPWbdj387TXK3NmbJdZ/34FvwfvOUOogiaGOX3KVJeb32a7bFayEuNQRiK5Feh8/+QYAj5KOM4jl8jM7rIxMFId58AtBOYUoCG6ZnNL2hBfL9Mw5nm0IqhUGNxBHIDLPQWNo70O6tr/FDlrM1CBHwj23XY8sfNqjDwXwVEuEi/N7J6lTTuLin8WUUO8hki0qoOVRh9Eu9q8zCLQYl0OJWtHsuRgecKJaU5ck90K0V6UZdxjrJmK0cCbfN1+xOr3MuxZdgWpmyVY6u6lMOfVYq+GpDkqb9VL0/JcpIDSWQnYvbpY/Rg+xYmytoEGDvF/4LTvdvQDeoCFuLQ71k18V5pBa0uV1thTRiyu2k52UDb4xKORMdbdu2m7IV0OT9Y4PmpYyRwkV5sKMNiXcaSoGL+FJ2MOdCOq/53uXMTzRRPRWH5lF/1QnRY7JA/OjiOnyIwJfyQLUAL7h2iohIaPzxueXDpqWYjFhAWlxM1GnA9eTeGX93AK7GPzv2geIv9A2Tzk59ZBNYv5dFCodZln3euPIiEgu6+5ILzXY/dGVVcLce1mqYsEkAS0BGywQuXxMx1HrwK1YcTyMdLzEKMLrgWoJW+v/zsbUqZXS+sayGlWmAvWYJPNUmjykFrL8LEy7qQqGUCAX3LvC1BhCfNSUsxeFrfSTYvkNEPJkYzt/aMYXyfAUCS4mJE7DhrY/LaJptmORAGm+SJVKS1LeHBU/9WgAh4K9/jNW/ei0TKrYLlL8mczyB/qYSifN8dwXRivY9BA+xczl8smHofbTro/mL8dgbWm43vnNxX/U0Ow4F3uGGklA4DlYaw==
  template:
    metadata:
      name: v2ray-config
      namespace: v2ray-vpn
    type: Opaque
