apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wildcard-mseung-dev
  namespace: web-proxy
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`.+\.mseung\.dev`) || Host(`mseung.dev`)
      kind: Rule
      services:
        - name: max-proxy
          port: 80
  tls:
    secretName: mseung-wildcard-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wildcard-seung-dev
  namespace: web-proxy
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`.+\.seung\.dev`) || Host(`seung.dev`)
      kind: Rule
      services:
        - name: max-proxy
          port: 80
  tls:
    secretName: seung-wildcard-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: code-dsns-dev
  namespace: web-proxy
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`code.dsns.dev`)
      kind: Rule
      services:
        - name: code
          port: 7799
  tls:
    secretName: dsns-wildcard-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-dsns-dev
  namespace: web-proxy
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`immich.dsns.dev`)
      kind: Rule
      services:
        - name: immich
          port: 2283
  tls:
    secretName: dsns-wildcard-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vray-dsns-dev
  namespace: web-proxy
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vray.dsns.dev`)
      kind: Rule
      services:
        - name: vray
          port: 10086
  tls:
    secretName: dsns-wildcard-tls
