apiVersion: v1
kind: Service
metadata:
  name: lan-218-http
  namespace: web-proxy
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: lan-218-http
  namespace: web-proxy
subsets:
  - addresses:
      - ip: 10.3.3.218
    ports:
      - name: http
        port: 80
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: code
  namespace: web-proxy
spec:
  ports:
    - name: http
      port: 7799
      targetPort: 7799
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: code
  namespace: web-proxy
subsets:
  - addresses:
      - ip: 10.3.3.195
    ports:
      - name: http
        port: 7799
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: immich
  namespace: web-proxy
spec:
  ports:
    - name: http
      port: 2283
      targetPort: 2283
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: immich
  namespace: web-proxy
subsets:
  - addresses:
      - ip: 10.3.3.172
    ports:
      - name: http
        port: 2283
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: vray
  namespace: web-proxy
spec:
  type: ExternalName
  externalName: v2ray-service.v2ray-vpn.svc.cluster.local
  ports:
    - name: http
      port: 10086
      targetPort: 10086
      protocol: TCP
