apiVersion: v1
kind: Service
metadata:
  name: max-proxy
  namespace: web-proxy
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: max-proxy
  namespace: web-proxy
  labels:
    kubernetes.io/service-name: max-proxy
addressType: IPv4
ports:
  - name: http
    port: 80
    protocol: TCP
endpoints:
  - addresses:
      - 10.3.3.218
---
apiVersion: v1
kind: Service
metadata:
  name: code
  namespace: web-proxy
spec:
  ports:
    - name: http
      port: 7799
      targetPort: 7799
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: code
  namespace: web-proxy
  labels:
    kubernetes.io/service-name: code
addressType: IPv4
ports:
  - name: http
    port: 7799
    protocol: TCP
endpoints:
  - addresses:
      - 10.3.3.195
---
apiVersion: v1
kind: Service
metadata:
  name: immich
  namespace: web-proxy
spec:
  ports:
    - name: http
      port: 2283
      targetPort: 2283
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: immich
  namespace: web-proxy
  labels:
    kubernetes.io/service-name: immich
addressType: IPv4
ports:
  - name: http
    port: 2283
    protocol: TCP
endpoints:
  - addresses:
      - 10.3.3.172
---
apiVersion: v1
kind: Service
metadata:
  name: vray
  namespace: web-proxy
spec:
  type: ExternalName
  externalName: v2ray-service.v2ray-vpn.svc.cluster.local
  ports:
    - name: http
      port: 10086
      targetPort: 10086
      protocol: TCP
