github:
  owner: dsnsgithub
  repo: homelab
  labels:
    - preview
  secretName: github-pr-generator-token
  secretKey: token

generator:
  requeueAfterSeconds: 120
  repoURL: https://github.com/dsnsgithub/homelab.git
  # web-proxy is excluded (shared routing).
  directories:
    - path: apps/*
    - path: apps/web-proxy
      exclude: true
