---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    {{- toYaml .Values.sealedSecret.encryptedData | nindent 4 }}
  template:
    metadata:
      name: cloudflare-api-token
      namespace: {{ .Values.namespace }}
    type: Opaque