namespace: web-proxy
createNamespace: true

# Backends proxied by Traefik, including bare-metal/VMs and in-cluster targets.
traefikServices:
  - name: max-proxy
    url: http://10.3.3.218:80
  - name: code
    url: http://10.3.3.195:7799
  - name: immich
    url: http://10.3.3.172:2283
  - name: vray
    url: http://v2ray-service.v2ray-vpn.svc.cluster.local:10086

ingressRoutes:
  - name: wildcard-mseung-dev
    match: HostRegexp(`.+\.mseung\.dev`)
    service: max-proxy
    tlsSecret: mseung-wildcard-tls
  - name: wildcard-seung-dev
    match: HostRegexp(`.+\.seung\.dev`)
    service: max-proxy
    tlsSecret: seung-wildcard-tls
  - name: code-dsns-dev
    match: Host(`code.dsns.dev`)
    service: code
    tlsSecret: dsns-wildcard-tls
  - name: immich-dsns-dev
    match: Host(`immich.dsns.dev`)
    service: immich
    tlsSecret: dsns-wildcard-tls
  - name: vray-dsns-dev
    match: Host(`vray.dsns.dev`)
    service: vray
    tlsSecret: dsns-wildcard-tls

certificates:
  - name: wildcard-dsns-dev
    secretName: dsns-wildcard-tls
    dnsNames:
      - dsns.dev
      - "*.dsns.dev"
  - name: wildcard-mseung-dev
    secretName: mseung-wildcard-tls
    dnsNames:
      - mseung.dev
      - "*.mseung.dev"
  - name: wildcard-seung-dev
    secretName: seung-wildcard-tls
    dnsNames:
      - seung.dev
      - "*.seung.dev"