apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-server-lb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dsnsgithub/homelab.git
    targetRevision: main
    path: charts/argocd-server-lb
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
