---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-pr-generator-token
  namespace: argocd
spec:
  encryptedData:
    token: AgBMJYD+Ov5oY3anW+Mf6LYunIQ998jVPaXEQZLkKQegImMJjr02xHynJMJ9IgIhdBERV5UKpLiU8TemZIK948C/z/EIUNrNXEwXJpA4OJYAULV9aH4oHQk53wDR2QWBnveU2YV+z4i+ezjkp3/dmIEv6Tyrc4nNuv45FLGYB335dDuv5K1BJziGKuEJD5kSTbJmKpxJt6cdUA7Ul0gIBwlxxmMfdDjW18Qk/V6LUW3jBPhHP/kZCTDI85v362ovOon0M1KIwaGjQyoOn0molk2qrqihjFbAsl0rAv703wz9bKI9Y+8e0UluiazhpS+7uhIR2UCx0NIOTQIFSMFBXvCoO8aM4xTXNHjRFnJSFdpP27nW91JXpvPy/xQVUpeNlzVzQ71Ww7fwa0a6XZCNpNQl78vtgxTiRsvMURd/RBJ/8M34X0B8tLUjH75GTnKAhR4rIlHM0YHqUxntCIJbex7snPoiIx12DxXR4dLUZzyS+JR3APu2lrkN5f/dtM2CX1R+SnHca1dGYJCs4ubxJH2MBHjH2foGnQlMPOyncWj9ijtqH6zaN9vPqWdpiCffP9ttYl3LcU6d790u4MN1VZBgLAuadn5PjqtRl0TG5CsHNx9Tz9Y/PuCdMdGQgp3Sd+LmtDMVKzQ4dEQjpPzqSIFWxNdgLiYl94udmEHQCOvAdV8YWU2d+7XlRiEYpFr9cCZYJ4PfOZH+QGRKyzeIyQCtQ30ePQwxriZakFYWZb8EOSAkQ7KTH9AQBhGREZOvyaAAkzezrXOsK/YbNnAzUyzPeYGhkmnnteNHr1KbNEFYnm4R2wj+IraHubmT0wg=
  template:
    metadata:
      name: github-pr-generator-token
      namespace: argocd
    type: Opaque
