apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  sources:
    - repoURL: https://kube-vip.github.io/helm-charts
      chart: kube-vip
      targetRevision: 0.11.1
      helm:
        valueFiles:
          - $homelab/infra/kube-vip/values.yaml
    - repoURL: https://github.com/dsnsgithub/homelab.git
      targetRevision: main
      ref: homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
