apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.nginx.com/stable
      chart: nginx-ingress
      targetRevision: 2.7.3
      helm:
        skipCrds: true
        valueFiles:
          - $homelab/infra/nginx-ingress/values.yaml
    - repoURL: https://github.com/dsnsgithub/homelab.git
      targetRevision: main
      ref: homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
