apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.traefik.io/traefik
      chart: traefik
      targetRevision: 41.5.0
      helm:
        valueFiles:
          - $homelab/infra/traefik/values.yaml
    - repoURL: https://github.com/dsnsgithub/homelab.git
      targetRevision: main
      ref: homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
