apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-secret
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dsnsgithub/homelab.git
    targetRevision: main
    path: infra/traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
