apiVersion: v1
kind: Service
metadata:
  name: limbo-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: limbo
  ports:
  - name: limbo
    port: {{ .Values.service.limboPort }}
    targetPort: {{ .Values.service.limboPort }}