apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-proxy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mc-proxy
  template:
    metadata:
      labels:
        app: mc-proxy
    spec:
      initContainers:
      - name: init-configs
        image: busybox:latest
        command: ['sh', '-c', 'cp /config-source/velocity.toml /server/velocity.toml && cp /config-source/forwarding.secret /server/forwarding.secret']
        volumeMounts:
        - name: server-data
          mountPath: /server
        - name: config-source
          mountPath: /config-source
      containers:
      - name: proxy
        image: {{ .Values.proxy.image | quote }}
        env:
        - name: TYPE
          value: "VELOCITY"
        - name: MINECRAFT_VERSION
          value: {{ .Values.proxy.minecraftVersion | quote }}
        - name: MODRINTH_PROJECTS
          value: |
            velocity-limbo-handler
            simple-voice-chat:alpha
        ports:
        - containerPort: 25577
          name: velocity
        - containerPort: 25577
          protocol: UDP
          name: voice-chat
        volumeMounts:
        - name: server-data
          mountPath: /server
        stdin: true
        tty: true
      volumes:
      - name: server-data
        emptyDir: {}
      - name: config-source
        secret:
          secretName: velocity-config
