apiVersion: v1
kind: Service
metadata:
  name: v2ray-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: v2ray
  ports:
  - name: v2ray
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}