{{- range .Values.ingressRoutes }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ .match }}
      kind: Rule
      services:
        - kind: TraefikService
          name: {{ .service }}
  tls:
    secretName: {{ .tlsSecret }}
{{- end }}