{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  ports:
    - name: http
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    kubernetes.io/service-name: {{ .name }}
addressType: IPv4
ports:
  - name: http
    port: {{ .port }}
    protocol: TCP
endpoints:
  {{- range .endpoints }}
  - addresses:
      - {{ . }}
    conditions: {}
  {{- end }}
{{- end }}