---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-cloudflare
  namespace: kube-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgByeDmKDAmqfmfLbk4N/2Sjvcgt1i1JntDMt4GWr7h/K0C/55eVNPA4cq6DYZYqqQoPddjfb25j1EbV5/T+PWiVeKj4VGgshuDHFds+3FHC4m3rsZZm/BXvJqcYO6VCuX6A6TzqTV1frgL7FAk9JUleKE5ZKddkunIKMsLoeMZA3n18uKVfFSl7gocdkRggcmhxxQ8byuCdptB6xCLvQR65pZwk4KY1IcFKCPk9xHVZx348iNpiWjOXZr5YSRmqjdR+YaL7iadcAJhsAyyf+NcqJwQ0utvn1v/M+rudBxkijwHywsQzfOwahiiAmmxQUNAbDe6SCn13wcqIpkVxUjHxH2OgrXYOK7opiLX+O3YXZwlFY5qJZxBIeb4jB3P3vf0RDpbtAy9M1QTrXn+IIxJNJoc3f8+cJPigz0CgReAdV/Fna7mjqf1F5D+M9LMgsHVdd91wEGX2EnhWwIXbgJBypHPZNKQjyptAyvazqb1hbPrfJRAHgs+9J3rAeHXq4Af9zxfcs6Z2IxZbuqE39q6QbQK/4B8hckzWgYzWdq6rTxR0W6I1xnpgmJDWc4M6aHNyp8QLLc4HUN3rU1sSdz3p/ucCriyZeBHoELb5ZnuRqus/mVi7eNsGY7bNKfaL/N/pwyLqE0kkw7LO0/Q1wu+xTwZPoDIX77Ap0yc5D1nwpG7tJ/xRu/Pv3eCYWkBjFtjHL1YvzBvP7VdSCYSRWpKU5aRtdlVtRdM8HsJSkCJU9zgA89JpzWIe
  template:
    metadata:
      name: traefik-cloudflare
      namespace: kube-system
    type: Opaque
