deployment:
  replicas: 2

providers:
  kubernetesCRD:
    allowExternalNameServices: true

service:
  labels:
    homelab.dsns.dev/load-balancer: cilium
  annotations:
    lbipam.cilium.io/ips: "10.3.3.10"
  spec:
    externalTrafficPolicy: Cluster

ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
