apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - velocity-secret.sealed.yaml
  - limbo-deployment.yaml
  - limbo-service.yaml
  - mc-proxy-a-deployment.yaml
  - mc-proxy-b-deployment.yaml
  - mc-proxy-a-service.yaml
  - mc-proxy-b-service.yaml
  - mc-proxy-pdb.yaml
