apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - velocity-secret.sealed.yaml
  - limbo-deployment.yaml
  - limbo-service.yaml
  - mc-proxy-statefulset.yaml
  - mc-proxy-services.yaml
  - mc-proxy-pdb.yaml
