apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-proxy
  namespace: minecraft
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mc-proxy
  template:
    metadata:
      labels:
        app: mc-proxy
    spec:
      initContainers:
      - name: init-configs
        image: busybox:latest
        command: ['sh', '-c', 'cp /config-template/velocity.toml /server/velocity.toml && cp /forwarding-secret/forwarding.secret /server/forwarding.secret']
        volumeMounts:
        - name: server-data
          mountPath: /server
        - name: velocity-config-template
          mountPath: /config-template
        - name: forwarding-secret
          mountPath: /forwarding-secret
      containers:
      - name: proxy
        image: itzg/mc-proxy:java25
        env:
        - name: TYPE
          value: "VELOCITY"
        - name: MINECRAFT_VERSION
          value: "26.2"
        - name: MODRINTH_PROJECTS
          value: |
            velocity-limbo-handler
            simple-voice-chat:alpha
        ports:
        - containerPort: 25577
          name: velocity
        - containerPort: 25577
          protocol: UDP
          name: voice-chat
        volumeMounts:
        - name: server-data
          mountPath: /server
        stdin: true
        tty: true
      volumes:
      - name: server-data
        emptyDir: {}
      - name: velocity-config-template
        configMap:
          name: velocity-config
          items:
          - key: velocity.toml
            path: velocity.toml
      - name: forwarding-secret
        secret:
          secretName: velocity-forwarding-secret
          items:
          - key: forwarding.secret
            path: forwarding.secret
