---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: velocity-forwarding-secret
  namespace: minecraft
spec:
  encryptedData:
    forwarding.secret: AgAvC5BTRPZj6finP45ZIJtAaB21yoW41NiD+cslBMz6siQw6lmUXPy2o1DhLIDFvI+CW95RHAexYbK1HyfTbiMGzbT50hCutKI1/t9+Adku527CMQAv6dSxQr412YRKWYjonzFDUWipTSQRCeR4Mo0mviDiV967aeSk/+oSy2XEgtW054rMCBmKZlZvj890n3XOppqlgl8AXtmi5+jVas9rMbkdn4TjrqEehkk5YIuuOYoBDzTdfRPnXRJgUSTRDdTqw/BVFq5YqpLlfrShmaXLrdFsjVJ6dEvJUTRDoE1NuRlMZo9QqvxRrJy8sBLIVY96YyKrKoqDcFP4mA+2a1KA8a6cn1Nrc1abgXtZs53mP8Y2547SEVNvzX8mK09UIq9P+KQ+BbXIAQA1Jnso+d9z8cI/w+YtRtmW3YNeIC0KhIu/uW0FzH59+IIrGOmB0UdSg4o2OgBULYYa8A/x45okb1GRVNHFpdUMLZ48CmYWx8haGXkg8RKnomSyg/PXiWT18d2oZz75UB2MUQfS8bWyuWl30UXuTO+os/yBoGJvfMFSUxl2R7Qfix6I2aJcLGSCk/O5kE9y4eY6phsDY2zI3ZDkCdWWI1JGNMtyAj9cz1ftAsOFdW3Nr+xveBX+4/AUDXrtasDZeQpj/x4MfAHpVZLB1mJuLDN1dAJLtGlnVnspTV0jm78GgwfJHC/EGE8u2p8/7gyoK4Ub7d4rxsfJV1Plw+GExzMErUHxXAPmlg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: velocity-forwarding-secret
      namespace: minecraft
    type: Opaque
