---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velocity-forwarding-secret
  namespace: minecraft
spec:
  encryptedData:
    forwarding.secret: AgB7q+iWjD8Ja5uVRfLdRm9s52j0KuaJVs2HPlgiEXGIRQ0j8xzx7WtRwGvpHgbqj7Z9YYMHDprNTKqv/506b1UefaEyWqceZmcnPy3dWtGvlJcfp91HXERcAixZSLVoEmIrrQ8O1+HithugOmmrlwEjd6Ll2iCSski1QoHSYpLJHZZWsLjcT4TK2EEhPopFd2kqL7YzWGackERwDGmuJ2zfIKbiv2jO1gYUVnggfO6FiSs/glpz8F7ThRlc/co63i7I71jo1sP+9CS1LK+y5adhqezpnVlh1cmvGxC1m0NSjHrXhrwdYmYgXopPnuM8G8hwT63AUo2PIWSmoiO+5fPENLYpYE2sMkomSUtgkuebMhMks0C8bsHiNUYzBwlMgkXVsA7x2S84L+ilHiEE1otpT4VKZNwVy7i7F7JUFbAzKHd3G/0vClDG+h3B4/EsSdh43bkeRFolFHem2/BwP2KWC8lFeDq6Eu6kJX2t5izbACzaZXaLCaWVJn3OL65E5MKAcnqn/jOfOdhaweU7g2tHT6fsioJEDciZ6x8o0/z++sB73ni7JPDrLW2c+WAyk3sIWFzk7GAdV04AJY4MNG425B/7AFS7jaY3tJQQy5/3F7Sr+xwQxCjXbvojIUd7cPddDaWPPEnuR0bDLldH7Vm/+IozZj6mmGCcZ6cej3ss5esO8yqnXPPICNOOGcIq6PogOmCdbVt1ANQkzH6CEBxmq6MvNq1D2wYDHEXZobE62g==
  template:
    metadata:
      name: velocity-forwarding-secret
      namespace: minecraft
    type: Opaque
