---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velocity-forwarding-secret
  namespace: minecraft
spec:
  encryptedData:
    forwarding.secret: AgBNbJTB/NIC3D/Iudt1KX1SCq0qbdCfKem64w0ILIgMS3vFqzBt4EmKrYPnXMbEcGO/8zeyyjPrmQmhlP4XHAgQ5Y87uxyFUwMTjp0yY2isgDz1bIln/XtJQY/UYacQd3sRkmkgK+c4g32M4h47hZSIuzz4t2pNG59cN5f6FdDzEmh2N+IL9tF0hz1nNhx1sEncgEb4RtVX5sQEJoeH1s1vjMJzY3shg6FA/4rv4EmRjSS4D9NYcE52OxtmqKfyilftTLJnVHhmto8FmX4I6H8ThxPp2Kb48hc3pB5Pe0R5azzUQHY+d6EGm2cbcIbdHysBuy5yqwrA5uw8i1NiHU88EYdFXXOxiTP/vUFUxuPxVVgXKqwQXq27vKlthM4QiNizVKDojVqpTF5UZ4MTH75uCgQfhZZ1eBmyc33nRsbzfuBVumulb/KpD4ID2Jkrvql3u2zadm/E+5uAyjWBGYl4zGguRFrQ2m/AGDM9vv9s/q+HsJ9NQ040bf+CL73VQFhkMiClkSqdX6AlESWc1tP7JMMsyRt08S49pAOAIpNn7VLUClw0u4GtU7Jwa47DIKYWlCvLnj8U3WmzEtgAbgvvg7d36qPqXO9QqTHNnIJMz/k0JxCApW7XUdiwbZAKyL7hhRN6B/IrjqkD9/EGAGfKL9uamD4AsR7KOyxnfc4TC1X5ESMoz6RenoUgvgZtR+o/HoHrqmSYijKwq4mE+dk98xZGe7qs2S99xPXe5EaJNjo=
  template:
    metadata:
      name: velocity-forwarding-secret
      namespace: minecraft
    type: Opaque
